version: '3.9'
services:
  # docker-compose -f docker-compose.yml up
  important:
    image: python:3.10-alpine
    working_dir: /code
    ports:
      - "10000:10000"
    volumes:
      - ./:/code
    entrypoint: ["/bin/sh","run.sh"]
