name: Build App
on:
  push:
    branches:
      - main
      - develop
      - feature-default-github-actions

jobs:
  application_test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code.
        uses: actions/checkout@v3

      - name: Check environment.
        run: |
          ls -ltra
          python --version
          pip --version

      - name: Install dependencies.
        run: |
          pip install -r requirements.txt

  oscal_validate:
    runs-on: ubuntu-20.04
    steps:
      - name: Execute OSCAL Validation
        id: oscal-validation
        uses: ./.github/actions/oscal-validation

      - name: Run tests.
        run: |
          pytest

  oscal_assessment:
    runs-on: ubuntu-20.04
    steps:
      - name: Start application.
        run: |
          cd app
          docker-compose -f docker-compose.yml --profile=testing up -d

      - name: Execute OSCAL Assessment Plan
        id: oscal-assessment-plan
        uses: ./.github/actions/oscal-assessment-plan-execute
        with:
          oscal-assessment-plan: '.oscal/assessment-plan/sample-plan.yaml'

      - name: Shut down application.
        run: |
          cd app
          docker-compose -f docker-compose.yml --profile=testing down

  oscal_result:
    runs-on: ubuntu-20.04
    steps:
      - name: Get the output information from Assessment Execution
        run: |
          echo "The time was ${{ steps.oscal-assessment-plan.outputs.time }}"
          echo "The location was ${{ steps.oscal-assessment-plan.outputs.location }}"
          echo "The file was ${{ steps.oscal-assessment-plan.outputs.model }}"